name: Update Sitemap

on:
  schedule:
    - cron: "0 0 * * *"  # Update setiap hari jam 00:00 UTC
  workflow_dispatch:      # Bisa dijalankan manual dari GitHub
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate sitemap.xml
        run: |
          curl -s "https://zonainfotips.blogspot.com/atom.xml?redirect=false&start-index=1&max-results=500" \
          | grep -Eo '<link rel=.alternate.*href=.https[^"]+' \
          | sed -E 's/.*href=.//g' \
          | awk 'BEGIN {
              print "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
              print "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">"
            }
            {print "  <url><loc>" $0 "</loc></url>"}
            END {print "</urlset>"}' > sitemap.xml

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap"
          git push
